server:
  port: 2022

spring:
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      routes:
        - id: UserService
          uri: lb://UserService
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: UserService
                fallbackuri: forward:/userfallback

        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path=/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: ProductService
                fallbackuri: forward:/productfallback

        - id: DepartmentService
          uri: lb://DepartmentService
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DepartmentService
                fallbackuri: forward:/departmentfallback


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream